config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  get "welcome/index"
  
  resources :articles, only: [:show] do
    resources :comments do
      member do
        post :like
        post :dislike
      end
    end
  end
  

  namespace :administrate do
    get "/", to: "dashboards#index"

    resources :authors do
       member do
         delete :destroy_avatar_image
       end
     end
 

    resources :articles do
      member do
        delete :destroy_cover_image
      end
    end


    resources :categories do
      member do
        delete :destroy_cover_image
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/inicio", to: "welcome#index"

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/author.rb
# frozen_string_literal: true

class Author < ApplicationRecord
  has_many :articles, dependent: :nullify
  has_one_attached :avatar_image
end

app/controllers/administrate/articles_controller.rb
# frozen_string_literal: true

module Administrate
  class ArticlesController < AdministrateController
    before_action :set_article, only: [:show, :edit, :update, :destroy, :destroy_cover_image]
    before_action :set_categories, only: [:new, :edit, :show]
    before_action :set_authors, only: [:new, :edit, :show]

    # GET /articles or /articles.json
    def index
      @articles = Article.includes(:category).all
    end

    def set_authors
      @authors = Author.all
    end

    # GET /articles/1 or /articles/1.json
    def show
    end

    # GET /articles/new
    def new
      @article = Article.new
    end

    # GET /articles/1/edit
    def edit
    end

    # POST /articles or /articles.json
    def create
      @article = Article.new(article_params)
      @article.cover_image.attach(article_params[:cover_image])

      respond_to do |format|
        if @article.save
          format.html { redirect_to([:administrate, @article], notice: "Artigo criado com sucesso!") }
          format.json { render(:show, status: :created, location: @article) }
        else
          format.html { render(:new, status: :unprocessable_entity) }
          format.json { render(json: @article.errors, status: :unprocessable_entity) }
        end
      end
    end

    # PATCH/PUT /articles/1 or /articles/1.json
    def update
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to([:administrate, @article], notice: "Artigo atualizado.") }
          format.json { render(:show, status: :ok, location: @article) }
        else
          format.html { render(:edit, status: :unprocessable_entity) }
          format.json { render(json: @article.errors, status: :unprocessable_entity) }
        end
      end
    end

    # DELETE /articles/1 or /articles/1.json
    def destroy
      @article.destroy!

      respond_to do |format|
        format.html { redirect_to(administrate_articles_path, status: :see_other, notice: "Artigo apagado.") }
        format.json { head(:no_content) }
      end
    end

    def destroy_cover_image
      @article.cover_image.purge

      respond_to do |format|
        format.turbo_stream { render(turbo_stream: turbo_stream.remove(@article)) }
      end
    end

    private

    def set_categories
      @categories = Category.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(
        :title,
        :body,
        :cover_image,
        :category_id,
        :author_id,
      )    end
  end
end

app/controllers/administrate/authors_controller.rb
# frozen_string_literal: true

module Administrate
  class AuthorsController < AdministrateController
    before_action :set_author, only: [:show, :edit, :update, :destroy, :destroy_avatar_image]
    def index
      @authors = Author.all
    end

    # GET /authors/1 or /authors/1.json
    def show
    end

    # GET /authors/new
    def new
      @author = Author.new
    end

    # GET /authors/1/edit
    def edit
    end

    # POST /authors or /authors.json
    def create
      @author = Author.new(author_params)
      @author.avatar_image.attach(author_params[:avatar_image])    
      respond_to do |format|
        if @author.save
          format.html { redirect_to(administrate_author_url(@author), notice: "Autor criada com sucesso!") }
          format.json { render(:show, status: :created, location: @author) }
        else
          format.html { render(:new, status: :unprocessable_entity) }
          format.json { render(json: @author.errors, status: :unprocessable_entity) }
        end
      end
    end

    # PATCH/PUT /Authors/1 or /Authors/1.json
    def update
      respond_to do |format|
        if @author.update(author_params)
          format.html { redirect_to(administrate_author_url(@author), notice: "Autor atualizado com sucesso!") }
          format.json { render(:show, status: :ok, location: @author) }
        else
          format.html { render(:edit, status: :unprocessable_entity) }
          format.json { render(json: @author.errors, status: :unprocessable_entity) }
        end
      end
    end

    # DELETE /Authors/1 or /Authors/1.json
    def destroy
      respond_to do |format|
        format.html do
          if @author.articles.count > 0
            redirect_to(
              administrate_authors_url,
              alert: "Existem Artigos associados a esse Autor. Não é possível apagá-lo.",
            )
          else
            @author.destroy!
            redirect_to(administrate_authors_url, notice: "Autor apagada com sucesso!")
          end
        end
        format.json { head(:no_content) }
      end
    end

    def destroy_avatar_image
      @author.avatar_image.purge

      respond_to do |format|
        format.turbo_stream { render(turbo_stream: turbo_stream.remove(@author)) }
      end
    end

    private

    def set_author
      @author = Author.find(params[:id])
    end

    def author_params
      params.require(:author).permit(
        :name,
        :description,
        :facebook_profile_url,
        :instagram_profile_url,
        :twitter_profile_url,
        :linkedin_profile_url,
        :youtube_profile_url,
        :avatar_image,
      )
    end
  end
end

app/controllers/administrate/categories_controller.rb
# frozen_string_literal: true

module Administrate
  class CategoriesController < AdministrateController
    before_action :set_category, only: [:show, :edit, :update, :destroy, :destroy_cover_image]


    def index
      @categories = Category.all
    end

    # GET /categories/1 or /categories/1.json
    def show
    end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories or /categories.json
    def create
      @category = Category.new(category_params)
      @category.cover_image.attach(category_params[:cover_image])

      respond_to do |format|
        if @category.save
          format.html { redirect_to(administrate_category_url(@category), notice: "Categoria criada com sucesso!") }
          format.json { render(:show, status: :created, location: @category) }
        else
          format.html { render(:new, status: :unprocessable_entity) }
          format.json { render(json: @category.errors, status: :unprocessable_entity) }
        end
      end
    end

    # PATCH/PUT /categorys/1 or /categorys/1.json
    def update
      respond_to do |format|
        if @category.update(category_params)
          format.html { redirect_to(administrate_category_url(@category), notice: "Categoria atualizado com sucesso!") }
          format.json { render(:show, status: :ok, location: @category) }
        else
          format.html { render(:edit, status: :unprocessable_entity) }
          format.json { render(json: @category.errors, status: :unprocessable_entity) }
        end
      end
    end

    # DELETE /categorys/1 or /categorys/1.json
    def destroy
      respond_to do |format|
        format.html do
          if @category.categories.count > 0
            redirect_to(
              administrate_categories_url,
              alert: "Existem Artigos associados a essaa categoria. Não é possível apagá-la.",
            )
          else
            @category.destroy!
            redirect_to(administrate_categories_url, notice: "Categoria apagada com sucesso!")
          end
        end
        format.json { head(:no_content) }
      end
    end
    def destroy_cover_image
      @category.cover_image.purge

      respond_to do |format|
        format.turbo_stream { render(turbo_stream: turbo_stream.remove(@category)) }
      end
    end
    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :description, :cover_image)    end
  end
end

app/controllers/administrate/dashboards_controller.rb
# frozen_string_literal: true

module Administrate
  class DashboardsController < AdministrateController
    def index; end
  end
end

app/controllers/administrate_controller.rb
# frozen_string_literal: true

class AdministrateController < ApplicationController
  before_action :authenticate_admin!
  layout "administrate"

  
end

app/helpers/author_helper.rb
# frozen_string_literal: true
 
module AuthorHelper
  def avatar_image_fallback(author)
    author.avatar_image.attached? ? author.avatar_image : "avatar/avatar-1.png"
  end
end

app/views/administrate/authors/_author.html.erb
<tr>
   <td><%= author.name %></td>
   <td>
     <div class="icons">
       <%= link_to edit_administrate_author_path(author), title: "Editar", alt: "edit" do %>
         <%= image_tag "icons/gray/edit.svg" %>
       <% end %>
 
       <%= link_to [:administrate, author], title: "Visualizar", alt: "eye" do %>
         <%= image_tag "icons/gray/eye.svg" %>
       <% end %>
 
       <%= button_to [:administrate, author], title: "Apagar", class: "button-transparent", alt: "close", data: { turbo: false }, method: :delete do %>
         <%= image_tag "icons/gray/close.svg" %>
       <% end %>
     </div>
   </td>
 </tr>

app/views/administrate/authors/_form.html.erb
<div class="row">
   <%= form_with(model: [:administrate, author], class: "form", id: "author-form") do |form| %>
     <div class="input-row">
       <div class="input-container">
         <%= form.label :name, class:"label" %>
         <%= form.text_field :name, disabled: (params[:action] == "show"), placeholder:"Digite aqui o nome do autor", class:"input" %>
       </div>
     </div>
     <div class="input-row">
       <div class="input-container">
         <%= form.label :description, class:"label" %>
         <%= form.text_area :description, disabled: (params[:action] == "show"), placeholder:"Digite uma descrição para o autor", class:"input" %>
       </div>
     </div>
     <div class="input-row">
       <div class="input-container">
         <%= form.label :facebook_profile_url, class:"label" %>
         <%= form.text_field :facebook_profile_url, disabled: (params[:action] == "show"), placeholder:"Digite aqui a URL do perfil do facebook", class:"input" %>
       </div>
     </div>
     <div class="input-row">
       <div class="input-container">
         <%= form.label :instagram_profile_url, class:"label" %>
         <%= form.text_field :instagram_profile_url, disabled: (params[:action] == "show"), placeholder:"Digite aqui a URL do perfil do instagram", class:"input" %>
       </div>
     </div>
     <div class="input-row">
       <div class="input-container">
         <%= form.label :twitter_profile_url, class:"label" %>
         <%= form.text_field :twitter_profile_url, disabled: (params[:action] == "show"), placeholder:"Digite aqui a URL do perfil do twitter", class:"input" %>
       </div>
     </div>
     <div class="input-row">
       <div class="input-container">
         <%= form.label :linkedin_profile_url, class:"label" %>
         <%= form.text_field :linkedin_profile_url, disabled: (params[:action] == "show"), placeholder:"Digite aqui a URL do perfil do linkedin", class:"input" %>
       </div>
     </div>
     <div class="input-row">
       <div class="input-container">
         <%= form.label :youtube_profile_url, class:"label" %>
         <%= form.text_field :youtube_profile_url, disabled: (params[:action] == "show"), placeholder:"Digite aqui o nome do autor youtube", class:"input" %>
       </div>
     </div>
 
    <div>
       <%= form.label :avatar_image, style: "display: block", class: "label-input-file" %>
       <%= (form.file_field :avatar_image, style: "margin-bottom: 8px;") if params[:action] != "show" %>
 
       <div id=<%= dom_id(author) %>>
         <%= image_tag author.avatar_image if author.avatar_image.attached? %>
 
         <%= link_to "Remover",
               destroy_avatar_image_administrate_author_path(author),
               data: { "turbo-confirm": "Tem certeza?", "turbo-method": :delete } if author.avatar_image.attached? && params[:action] != "show" %>
       </div>
     </div>
 
     <%= button_to "Apagar autor", [:administrate, @author], data: { turbo: false }, method: :delete, class:"button small" if params[:action] == "show" %>  


     <%= form.submit style: "display: none;" %>
   <% end %>
 </div>

app/views/administrate/authors/edit.html.erb
<%= link_to "Autores", administrate_authors_path, class:"admin-title"%>
 <div class="main-content">
   <div class="row">
     <h2 class="admin-subtitle">Edição de autor</h2>
     <div class="buttons">
       <a href="#" class="button small" onclick="document.forms['author-form'].submit()">
         <%= image_tag "icons/white/save.svg", alt:"save" %>
         Salvar autor
       </a>
     </div>
   </div>
 
   <%= render "form", author: @author %>
 </div>

app/views/administrate/authors/index.html.erb
<h1 class="admin-title">Autores</h1>
 <div class="main-content">
   <div class="row">
     <h2 class="admin-subtitle">Listagem de autores</h2>
     <div class="buttons">
       <%= link_to new_administrate_author_path, class: "button small" do %>
         <%= image_tag "icons/white/add.svg", alt: "add" %>
         Adicionar novo autor
       <% end %>
     </div>
   </div>
   <div class="row">
     <table class="table">
       <thead>
         <tr>
           <th style="width: 100%">Nome</th>
           <th>Ações</th>
         </tr>
       </thead>
       <tbody>
         <% @authors.each do |author| %>
           <%= render author %>
         <% end %>
       </tbody>
     </table>
   </div>
 </div>

app/views/administrate/authors/new.html.erb
<%= link_to "Autores", administrate_authors_path, class:"admin-title"%>
 <div class="main-content">
   <div class="row">
     <h2 class="admin-subtitle">Cadastro de autor</h2>
     <div class="buttons">
       <a href="#" class="button small" onclick="document.forms['author-form'].submit()">
         <%= image_tag "icons/white/save.svg", alt:"save" %>
         Salvar autor
       </a>
     </div>
   </div>
 
   <%= render "form", author: @author %>
 </div>

app/views/administrate/authors/show.html.erb
<%= link_to "Autores", administrate_authors_path, class:"admin-title"%>
 <div class="main-content">
   <div class="row">
     <h2 class="admin-subtitle">Visualização de autores</h2>
     <div class="buttons">
       <%= link_to edit_administrate_author_path(@author), class:"button small" do %>
         <%= image_tag "icons/white/edit.svg", alt:"save" %>
         Editar autor
       <% end  %>
     </div>
   </div>
 
   <%= render "form", author: @author %>
 </div>